import Head from 'next/head'
import Image from 'next/image'
import s from '@/styles/Home.module.scss'
import { useState, useEffect } from 'react'
import AllForWork from './components/AllForWork/AllForWork'
import { IProduct } from '@/interfaces/interfaces'
import Product from './components/Product/Product'



export default function Home() {
  const [data, setData] = useState<IProduct[]>([])
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('https://fakestoreapi.com/products')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])
  
  return (
    <>
      <Head>
        <title>Azalia test task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>

        <div className={s.content}>
          <AllForWork />
          {data
            ? data.map((product: IProduct) => {
              return (
                <div key={product.id}>
                  <Product {...product}/>
                </div>
              )
            })
            : ""
          }
        </div>

      </main>
    </>
  )
}
